name: Sync with upstream

on:
  # schedule:
  #   - cron: "0 0 */7 * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - feature/native-comp

jobs:
  sync:
    name: Sync with upstream
    runs-on: ubuntu-latest
    env:
      upstream_repo: emacs-tree-sitter/tree-sitter-langs
      upstream_branch: master
    steps:
      - name: Clone
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.PAT_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone --filter=tree:0 $REPO .
      - name: Setup upstream
        run: |
          git remote add upstream https://github.com/$upstream_repo.git
          echo $upstream_branch | xargs -n1 | xargs -I{} git fetch upstream {} --filter=tree:0
      - name: Sync
        run: |
          git config --global user.email "github-actions[bot]"
          git config --global user.name "github-actions[bot]@users.noreply.github.com"
          echo $upstream_branch | xargs -n1 | xargs -I{} git merge --no-edit upstream/{}
          git push origin -f
